config/routes.rb
ToDo::Application.routes.draw do
  resources :users
  resources :tasks
  resources :tags, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'

  match 'signup' => 'users#new'
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag_name, :task_id

  validates_presence_of   :tag_name, message: "must be provided"
  validates_uniqueness_of :tag_name, case_sensitive: false,
                           message: "already exists"

  has_many :tag_tasks
  has_many :tasks, through: :tag_tasks

  has_many :users, through: :tasks

  def self.make_tag(value)
    Tag.where(tag_name: value).first || Tag.create(tag_name: value)
  end
end

app/models/tag_task.rb
class TagTask < ActiveRecord::Base
  attr_accessible :task_id, :tag_id

  belongs_to :task
  belongs_to :tag

  validates_uniqueness_of :tag_id, scope: :task_id
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :body, :title, :user_id

  validates_presence_of :user_id, message: "cannot be blank"
  validates_presence_of :body, message: "cannot be blank"
  validates_length_of   :body, maximum: 1000, message: "is too long"

  belongs_to :user

  has_many :tag_tasks, dependent: :destroy
  has_many :tags, through: :tag_tasks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :password, :password_confirmation,
                  :session_token, :completed_task_count

  validates_presence_of   :name, message: "cannot be blank"
  validates_length_of     :name, in: 1..30,
                          message: "must be between 1 and 30 characters"

  validates_presence_of   :email, message: "cannot be blank"
  validates_uniqueness_of :email, case_sensitive: false,
                          message: "is already registered"
  validates_format_of     :email,
                          with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
                          message: "is invalid"

  validates_length_of     :password, minimum: 8, on: :create,
                          message: "must be atleast 8 characters long"

  validates_presence_of   :password_confirmation,
                          if: :check_password_confirmation?,
                          message: "cannot be blank"

  has_many :tasks, dependent: :destroy
  has_many :tags, through: :tasks, dependent: :destroy

  def check_password_confirmation?
    password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def build_cookie(user)
    cookies[:user_id] = user.id
    user.update_attributes(session_token: SecureRandom.uuid)
    cookies[:token] = user.session_token
  end

  def current_user
    return nil if cookies[:user_id].nil? || cookies[:user_id] == ''
    return nil if cookies[:token].nil? || cookies[:token] == ''
    user = User.find(cookies[:user_id])
    return nil unless user
    return user if user.session_token == cookies[:token]
    return nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = User.new

    redirect_to user_path(current_user) if current_user
  end

  def create
    @user = User.find_by_email(params[:user][:email])

    if @user && @user.authenticate(params[:user][:password])
      build_cookie(@user)
      redirect_to user_path(@user)
    else
      flash.now[:notice] = "Invalid Username / Password"
      @session = User.new(params[:user])
      render 'new'
    end
  end

  def destroy
    if current_user
      current_user.session_token = nil
      cookies[:user_id] = nil
      cookies[:token] = nil
    end

    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @tasks = @tag.tasks if @tag
    
    if @tag && @tag.users.include?(current_user)
      render 'users/show'
    else
      redirect_to root_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    redirect_to root_path unless current_user

    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(params[:task])
    @task.tags << Tag.make_tag(params[:tag]) unless params[:tag].empty?

    if @task.save
      redirect_to user_path(current_user)
    else
      flash.now[:notice] = @task.errors.full_messages.first
      render 'new'
    end
  end

  def edit
    redirect_to root_path unless current_user

    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    begin
      @task.tags << Tag.make_tag(params[:tag]) unless params[:tag].empty?
    rescue ActiveRecord::RecordInvalid
      flash.now[:notice] = "Already tagged with #{params[:tag]}"
    end

    redirect_to user_path(current_user)
  end

  def destroy
    if current_user
      @task = Task.find(params[:id])
      current_user.tasks.delete(@task)
      task_count = current_user.completed_task_count + 1
      current_user.update_attributes(completed_task_count: task_count)

      redirect_to user_path(current_user)
    else
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.completed_task_count = 0

    if @user.save
      build_cookie(@user)
      redirect_to user_path(@user)
    else
      flash.now[:notice] = @user.errors.full_messages.first
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks

    unless @user==current_user
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=200"
    image_tag(gravatar_url, gravatar: { s: 200 }, alt: user.name, class: "gravatar")
  end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>.do</title>
  <link href='http://fonts.googleapis.com/css?family=Antic+Slab|Almendra+Display|Julius+Sans+One|Text+Me+One' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main">

  <% if current_user %>
    <div class="profile">
      <%= link_to 'http://gravatar.com/emails' do %>
        <div class="profile_pic_stub">
          Edit profile picture
        </div>
        <div class="profile_pic">
          <%= gravatar_for current_user %>
        </div>
      <% end %>
      <br>
      <h1><%= current_user.name %></h1>

      <div class="count">
        <%= current_user.completed_task_count %>
      </div>
      <div class="pre_count">
        Tasks completed:
      </div>
      <div class="clear_floats"></div>

      <div class="count">
        <%= current_user.tasks.length %>
      </div>
      <div class="pre_count">
        Tasks remaining:
      </div>
      <div class="clear_floats"></div>
      <span class="logout1">
        <%= link_to 'Logout', session_path(current_user), method: :delete %>
      </span>
      <span class="logout2">
        <%= link_to 'Logout', session_path(current_user), method: :delete %>
      </span>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= yield %>

</div>
<div class="footer"></div>

</body>
</html>

app/views/tags/show.html.erb
<h1 class="new_task"><%= @tag.tag_name %></h1>
<% @tag.tasks.each do |task| %>
  <%= link_to edit_task_path(task) do %>
    <div class="tag_show_task">
      <%= task.title %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <p>
    <%= f.label :title, "Title (optional)" %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body, "What do you want to do?" %>
    <%= f.text_area :body %>
  </p>
  <p>
    <% if @task.tags.any? %>
    <div class="pre_tag">
      Current tags:
    </div>
    <% end %>
    <% @task.tags.each do |tag| %>
      <div class="tag">
        <%= tag.tag_name %>
      </div>
    <% end %>
    <div class="clear_floats"></div>
  </p>
  <p>
    <%= label_tag :tag, "Add tag" %>
    <%= text_field_tag :tag %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    <%= link_to 'Cancel', user_path(current_user) %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<div class="task_form">
  <h1>Edit Task</h1>
  <%= render 'task_form' %>
</div>

app/views/tasks/new.html.erb
<div class="task_form">
  <h1>New Task</h1>
  <%= render 'task_form' %>
</div>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Sign up" %>
  </p>
<% end %>

app/views/users/new.html.erb
<div class='form'>
  <h1>Sign up</h1>
  <%= render 'user_form' %>
</div>
<div class="form_description">
  <h1>.do</h1>
  <p>/make tasks</p>
  <p>/add tags</p>
  <p>/be organized</p>
</div>

app/views/users/show.html.erb
<div class="task_list">
  <h1 class="task_list_title">Things you want to get done:</h1>

  <%= link_to new_task_path do %>
    <div class="user_show_add_task_link">
      Add a task
    </div>
  <% end %>

  <% if @user %>
    <div class="pre_tag">Tags:</div> 
    <% @user.tags.uniq.each do |tag| %>
      <%= link_to tag_path(tag) do %>
        <div class="tag">
          <%= tag.tag_name %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="pre_tag">Back to:</div>
    <%= link_to user_path(current_user) do %>
      <div class="tag">
        All tasks
      </div>
    <% end %>
  <% end %>
  <div class="clear_floats"></div>

  <div class="divider">&bull; &bull; &bull;</div>

  <% if @tasks.any? %>
    <% @tasks.each do |task| %>
      <div class="user_show_task">
        <% if task.title.empty? %>
          <h1>Do this</h1>
        <% else %>
          <h1><%= task.title %></h1>
        <% end %>

        <%= link_to edit_task_path(task) do %>
          <div class="user_show_task_link_left">edit</div>
        <% end %>

        <div class="clear_floats"></div>

        <p><%= task.body %></p>

        <%= link_to task_path(task), method: :delete do %>
          <div class="user_show_task_link_right">i got this done!</div>
        <% end %>

        <div class="clear_floats"></div>
      </div>

      <div class="divider">&bull; &bull; &bull;</div>
    <% end %>
  <% else %>
    <div class="user_show_task">
      No upcoming tasks
    </div>
  <% end %>
</div>